{{- $fullName := include "splunk.fullname" . -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
{{ include "splunk.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  port:
    targetPort: {{ $.Values.service.httpBindPort }}
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
